In [3]:
from pyspark.sql import SparkSession

In [4]:
spark = SparkSession.builder.getOrCreate()

In [11]:
data_path = "/Users/sangeethadetne/Desktop/BigData/SampleData/"

In [28]:
file_path = data_path +"Jan_2019_ontime.csv"

In [29]:
df1= spark.read.format("csv").option("header","true").load(file_path)

In [30]:
df1.show()

+------------+-----------+-----------------+---------------------+----------+--------+-----------------+-----------------+---------------------+------+---------------+-------------------+----+--------+---------+------------+--------+---------+---------+--------+--------+----+
|DAY_OF_MONTH|DAY_OF_WEEK|OP_UNIQUE_CARRIER|OP_CARRIER_AIRLINE_ID|OP_CARRIER|TAIL_NUM|OP_CARRIER_FL_NUM|ORIGIN_AIRPORT_ID|ORIGIN_AIRPORT_SEQ_ID|ORIGIN|DEST_AIRPORT_ID|DEST_AIRPORT_SEQ_ID|DEST|DEP_TIME|DEP_DEL15|DEP_TIME_BLK|ARR_TIME|ARR_DEL15|CANCELLED|DIVERTED|DISTANCE|_c21|
+------------+-----------+-----------------+---------------------+----------+--------+-----------------+-----------------+---------------------+------+---------------+-------------------+----+--------+---------+------------+--------+---------+---------+--------+--------+----+
|           1|          2|               9E|                20363|        9E|  N8688C|             3280|            11953|              1195302|   GNV|          10397|            1039707| ATL|    0601|     0.00|   0600-0659|    0722|     0.00|     0.00|    0.00|  300.00|null|
|           1|          2|               9E|                20363|        9E|  N348PQ|             3281|            13487|              1348702|   MSP|          11193|            1119302| CVG|    1359|     0.00|   1400-1459|    1633|     0.00|     0.00|    0.00|  596.00|null|
|           1|          2|               9E|                20363|        9E|  N8896A|             3282|            11433|              1143302|   DTW|          11193|            1119302| CVG|    1215|     0.00|   1200-1259|    1329|     0.00|     0.00|    0.00|  229.00|null|
|           1|          2|               9E|                20363|        9E|  N8886A|             3283|            15249|              1524906|   TLH|          10397|            1039707| ATL|    1521|     0.00|   1500-1559|    1625|     0.00|     0.00|    0.00|  223.00|null|
|           1|          2|               9E|                20363|        9E|  N8974C|             3284|            10397|              1039707|   ATL|          11778|            1177801| FSM|    1847|     0.00|   1900-1959|    1940|     0.00|     0.00|    0.00|  579.00|null|
|           1|          2|               9E|                20363|        9E|  N927EV|             3285|            11267|              1126702|   DAY|          13487|            1348702| MSP|    0853|     0.00|   0900-0959|    0953|     0.00|     0.00|    0.00|  574.00|null|
|           1|          2|               9E|                20363|        9E|  N915XJ|             3286|            12448|              1244807|   JAN|          10397|            1039707| ATL|    1553|     0.00|   1500-1559|    1832|     0.00|     0.00|    0.00|  341.00|null|
|           1|          2|               9E|                20363|        9E|  N295PQ|             3287|            12953|              1295304|   LGA|          11193|            1119302| CVG|    1551|     0.00|   1500-1559|    1824|     0.00|     0.00|    0.00|  585.00|null|
|           1|          2|               9E|                20363|        9E|  N337PQ|             3288|            12451|              1245102|   JAX|          12953|            1295304| LGA|    1037|     0.00|   1000-1059|    1239|     0.00|     0.00|    0.00|  833.00|null|
|           1|          2|               9E|                20363|        9E|  N311PQ|             3289|            10397|              1039707|   ATL|          10685|            1068502| BMI|    1245|     0.00|   1200-1259|    1318|     0.00|     0.00|    0.00|  533.00|null|
|           1|          2|               9E|                20363|        9E|  N311PQ|             3289|            10685|              1068502|   BMI|          10397|            1039707| ATL|    1410|     0.00|   1400-1459|    1700|     0.00|     0.00|    0.00|  533.00|null|
|           1|          2|               9E|                20363|        9E|  N931XJ|             3290|            10874|              1087402|   CAK|          10397|            1039707| ATL|    0557|     0.00|   0600-0659|    0737|     0.00|     0.00|    0.00|  528.00|null|
|           1|          2|               9E|                20363|        9E|  N800AY|             3291|            11433|              1143302|   DTW|          11267|            1126702| DAY|    1552|     0.00|   1500-1559|    1738|     1.00|     0.00|    0.00|  166.00|null|
|           1|          2|               9E|                20363|        9E|  N927EV|             3292|            13487|              1348702|   MSP|          11267|            1126702| DAY|    2029|     0.00|   2000-2059|    2259|     0.00|     0.00|    0.00|  574.00|null|
|           1|          2|               9E|                20363|        9E|  N600LR|             3293|            14100|              1410005|   PHL|          11433|            1143302| DTW|    1312|     0.00|   1300-1359|    1454|     0.00|     0.00|    0.00|  453.00|null|
|           1|          2|               9E|                20363|        9E|  N840AY|             3294|            12478|              1247805|   JFK|          14524|            1452401| RIC|    1450|     0.00|   1400-1459|    1637|     0.00|     0.00|    0.00|  288.00|null|
|           1|          2|               9E|                20363|        9E|  N232PQ|             3295|            11433|              1143302|   DTW|          11618|            1161802| EWR|    1353|     1.00|   1200-1259|    1521|     1.00|     0.00|    0.00|  488.00|null|
|           1|          2|               9E|                20363|        9E|  N8970D|             3296|            10208|              1020803|   AGS|          10397|            1039707| ATL|    1148|     0.00|   1100-1159|    1236|     0.00|     0.00|    0.00|  143.00|null|
|           1|          2|               9E|                20363|        9E|  N8970D|             3296|            10397|              1039707|   ATL|          10208|            1020803| AGS|    1020|     0.00|   1000-1059|    1111|     0.00|     0.00|    0.00|  143.00|null|
|           1|          2|               9E|                20363|        9E|  N304PQ|             3297|            11433|              1143302|   DTW|          11193|            1119302| CVG|    0817|     0.00|   0800-0859|    0932|     0.00|     0.00|    0.00|  229.00|null|
+------------+-----------+-----------------+---------------------+----------+--------+-----------------+-----------------+---------------------+------+---------------+-------------------+----+--------+---------+------------+--------+---------+---------+--------+--------+----+
only showing top 20 rows

In [60]:
df2 = df1.groupBy("DAY_OF_MONTH").count().orderBy("DAY_OF_MONTH").show()

+------------+-----+
|DAY_OF_MONTH|count|
+------------+-----+
|           1|18009|
|          10|19980|
|          11|20082|
|          12|15315|
|          13|18561|
|          14|19941|
|          15|18653|
|          16|19099|
|          17|19960|
|          18|20009|
|          19|14935|
|           2|20384|
|          20|16875|
|          21|19511|
|          22|18657|
|          23|19099|
|          24|19963|
|          25|20041|
|          26|15267|
|          27|18575|
+------------+-----+
only showing top 20 rows

In [66]:
df3 = df1.groupBy("DAY_OF_MONTH").agg({"DISTANCE":"max"}).orderBy("DAY_OF_MONTH").show()

+------------+-------------+
|DAY_OF_MONTH|max(DISTANCE)|
+------------+-------------+
|           1|       999.00|
|          10|       999.00|
|          11|       999.00|
|          12|       999.00|
|          13|       999.00|
|          14|       999.00|
|          15|       999.00|
|          16|       999.00|
|          17|       999.00|
|          18|       999.00|
|          19|       999.00|
|           2|       999.00|
|          20|       999.00|
|          21|       999.00|
|          22|       999.00|
|          23|       999.00|
|          24|       999.00|
|          25|       999.00|
|          26|       999.00|
|          27|       999.00|
+------------+-------------+
only showing top 20 rows

In [67]:
df4 = df1.groupBy("DAY_OF_MONTH").agg({"DISTANCE":"mean"}).orderBy("DAY_OF_MONTH").show()

+------------+-----------------+
|DAY_OF_MONTH|    avg(DISTANCE)|
+------------+-----------------+
|           1|846.9748459103781|
|          10|785.3841341341341|
|          11|784.3986654715666|
|          12|829.9539666993144|
|          13|803.7664457733958|
|          14|784.4130685522291|
|          15|774.9729802176594|
|          16|776.3545211791193|
|          17|785.3030060120241|
|          18|785.1225948323255|
|          19| 830.292802142618|
|           2|832.8632260596546|
|          20|811.9225481481482|
|          21|786.3522628260981|
|          22| 775.081953154312|
|          23|775.9946594062517|
|          24|785.6171417121675|
|          25|784.8686193303728|
|          26|830.1074867360975|
|          27|803.7272678331091|
+------------+-----------------+
only showing top 20 rows